build:
  image: i386/gcc:6.1
  before_script:
    - ./makemk.sh
    - export PATH=$PWD/arch/linux/386/bin/:$PATH
    - export MKFLAGS='SYSHOST=linux OBJTYPE=386 ROOT='$PWD
  script:
    - mk $MKFLAGS mkdirs
    - mk -depg -e -k $MKFLAGS install
    - emu cat /dev/sysctl

pages:
  image: rraghur/hugo-asciidoctor
  script:
    - cd sys/
    - hugo
  artifacts:
    paths:
    - public
  only:
  - master

