baseURL      = "https://inf.bryton.io/"
languageCode = "en-us"
title        = "inf"
contentDir   = "docs"
layoutDir    = "sys/layouts"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
[params]
tagline = "a distributed, virtualizable operating system"
#[params.color]
#main   = "#5d4d7a"
#accent = "#212026"
#link   = ""
#[menu]
#[[menu.left]]
#name = "portal"
#url = "https://inf.com"
#[[menu.left]]
#name = "source"
#url = "https://gitlab.com/hall/inf"
#[[menu.right]]
#name = "portal"
#url = "https://inf.com/hall/inf"
#[[menu.right]]
#name = "source"
#url = "https://gitlab.com/hall/inf"
